### ISSUE TITLE
DS3 host delivery service

### ISSUE THREAD

**Issue by AlexNi245** [dm3-org/dm3#785]
Now that the DS is part of an independent workspace there should be an easy way a DS operator can use one on its own. 

- [ ] Figure out how to make CLI scripts as accessible as possible
- [ ] Figure out how to make Deployment as easy as possible
- [ ] Add documentation that makes it easy to set up a DS

**Comment by malteish** [comment]
1. Provide docker container and docker-compose file to spin up local or remote instance
2. avoid: `wget xxx | sudo bash `

Necessary steps
1. **web app 1**: create keys and config from input data -> config.txt 
2. **web app 2**: load config.txt and publish to ens or offchain resolver 
3. on webserver: execute docker compose with fonfig.txt
4. (configure network -> this is the user's responsibility)

**Comment by malteish** [comment]
Some notes: https://www.notion.so/corpusventures/Delivery-service-f68b1796472045d09fb4662b1ec04190

**Comment by malteish** [comment]
> Thinking about the setup helper and the delivery service, I had a realization today. Currently, setting the service 
> up would work something like this:
>
> 1. get ENS
> 2. get domain
> 3. get wallet
> 4. use helper
> 5. copy files to some server or service
> 6. wget docker-compose.yml
> 7. docker compose up
> 
> I want it to work like this:
> 1. get domain (my-ds.org)
> 2. on server: docker run dm3-ds@latest
> 3. use browser to connect to my-ds.org/setup
> 4. finish setup there (you still need ens and wallet, but can follow the guide on your own instance, which feels much smoother and more trustworthy imo)

[link](https://corpusventures.slack.com/archives/C047JB95ZDZ/p1716567204341379)

Open questions:
1. Database. Redis is launched as a separate container. Either we use `docker compose`, then the user has to manually download a docker-compose file. Or we integrate the database into the delivery service container.
2. Volumes. The config and environment should persist, otherwise the setup step would have to be repeated every time. The same goes for the database.
3. How to bundle the setup helper. I creates files inside the container, which is potentially dangerous. How do we make it safe? How can it be bundled? How does node create files on the server?

**Comment by malteish** [comment]
Current state: web app v0.1 is ready. I need:

- Steffen and others to test the [web app](http://localhost:3000/). (check existing issues and add new issues [here](https://github.com/dm3-org/dm3-ds-setup-helper/issues))
- The delivery-service-image to be published. (Anyone who wants to test, please download and import this image into your local docker: [image](https://drive.google.com/file/d/1io1MWAy6z4DwKlwiC9OEef4u7OOvEsE8/view?usp=sharing))

**Comment by malteish** [comment]
done, though web app is just a poc atm
